### ISSUE TITLE
Proxy `add_object` method does not support signal/image metadata (e.g. ROI)

### ISSUE THREAD

**Issue by Charlesreve** [DataLab-Platform/DataLab#111]
I am using datalab V0.9.2. I would like to add/modify/delete ROIs to an image already loaded with a macro. 
There is no example with ROIs in the tutorials.
I know how to acces the ROIs of my image:

image = proxy.get_object(2)
data = np.array (image.data, copy=True)

and the ROIs are in image.roi.

I have tried : 

proxy.add_object(image) 

It saves the image with a new number, but without the ROIs.

Could you help ?

charlesreve

**Comment by PierreRaybaut** [comment]
Hi,

Thanks for the feedback.
This is a limitation of current implementation of the `add_object` method which is only passing data, title and labels (not metadata).

But, this has just been taken care of: we just added full support for signal and image objects!

Here's the proof:
![image](https://github.com/user-attachments/assets/4909942f-346e-4a38-8aeb-07dec81a43ce)

Would you be able to wait a few days for this feature?
This will be available in forthcoming v0.18.1.

Otherwise, you may also try the latest version using the `main` branch which is generally quite stable.

Cheers,
Pierre

**Comment by Charlesreve** [comment]
Thank you !
I’ll wait for v0.18.1.

De : Pierre Raybaut ***@***.***>
Envoyé : jeudi 5 décembre 2024 11:50
À : DataLab-Platform/DataLab ***@***.***>
Cc : REVERDIN Charles 087700 ***@***.***>; Author ***@***.***>
Objet : Re: [DataLab-Platform/DataLab] Region Of Interest (Issue #111)


Hi,

Thanks for the feedback.
This is a limitation of current implementation of the add_object method which is only passing data, title and labels (not metadata).

But, this has just been taken care of: we just added full support for signal and image objects!

Here's the proof:
image.png (view on web)<https://github.com/user-attachments/assets/4909942f-346e-4a38-8aeb-07dec81a43ce>

Would you be able to wait a few days for this feature?
This will be available in forthcoming v0.18.1.

Otherwise, you may also try the latest version using the main branch which is generally quite stable.

Cheers,
Pierre

**Comment by PierreRaybaut** [comment]
v0.18.1 has just been released
