### ISSUE TITLE
How to start DataLab

### ISSUE THREAD

**Issue by VincentLeroux** [DataLab-Platform/DataLab#53]
Once you install datalab using pip, how do you start DataLab GUI?

**Comment by PierreRaybaut** [comment]
It is actually mentioned in [this page](https://datalab-platform.github.io/en/features/general/command.html#run-datalab), but far away from the installation section (I'll add a "See also" and a link).

**Comment by VincentLeroux** [comment]
Thank you for the answer, and for this great project.
Just to mention it, I installed datalab alone in a virtual env, and then the command `cdl` did nothing.
After trying `python.exe -m cdl`, I got the Qt error: `qtpy.QtBindingsNotFoundError: No Qt bindings could be found`.
I could be fixed with `pip install pyqt5-tools`, and now `cdl` runs smoothly.

**Comment by PierreRaybaut** [comment]
Thanks for this additional info.

Actually, DataLab is based on an abstraction layer called `QtPy` which is compatible with `PyQt5`, `PyQt6` and `PySide6`. That's why there is no explicit dependency towards `PyQt5` and you have to install Qt bindings separately.

I understand that it can be confusing, especially since it's not mentioned in the documentation.

So I see two options:

1. Add `PyQt5` as an explicit dependency
2. Add something in the documentation like "After installing DataLab, you have to install Qt bindings (e.g. `pip install PyQt5`)."

What do you think about it?

**Comment by VincentLeroux** [comment]
I guess option 2 is easier and leaves more freedom.
People installing with pip tend to be more familiar with Python and can figure out easily if you just add in the "Getting Started > Installation > Package manager pip" section your option 2.
People that want a ready to use version (for which option 1 would be better) would tend to go for the all in one installer where you don't have this issue anyway.

**Comment by PierreRaybaut** [comment]
Ok, so here is a compromise.

We could add another option to install DataLab using `pip`:

- Install DataLab with Qt: `pip install cdl[qt]`
- Install DataLab without Qt (i.e. Qt bindings are already installed on your Python environment): `pip install cdl`

**Comment by VincentLeroux** [comment]
I didn't know that was possible but yeah, that's great!

**Comment by PierreRaybaut** [comment]
This *will* be possible in the next release 😉
(next week)

Thanks for your feedback

**Comment by PierreRaybaut** [comment]
By the way, @VincentLeroux, if you have a specific use case with DataLab and if you need help finding out how to use DataLab, please do not hesitate to share it. And if you can share some sample of your data, we may discuss around it and even write a tutorial based on it (that's exactly how most of the tutorials were written actually).

There is even an issue type for this: "Tutorial request".
