### ISSUE TITLE
Debian packaging for V0.16.3

### ISSUE THREAD

**Issue by PierreRaybaut** [DataLab-Platform/DataLab#89]
@rolandmas: Let's discuss here any issue regarding the [official Debian package](https://tracker.debian.org/pkg/datalab) related tasks.

This Issue will be closed once this package version is accepted into Debian unstable.

**Comment by rolandmas** [comment]
Source package uploaded and accepted into Debian unstable. It needs manual tweaks to build the binary packages because of a problem with a build-dependency in Debian (pydevd/debugpy, see https://bugs.debian.org/1075603), but once that is fixed datalab should get autobuilt and made available to users.

**Comment by PierreRaybaut** [comment]
Thanks again for your work! 👍
